name: CI

on:
  push:
    branches:
      - '**' # Matches every branch.

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x' 

      - name: Test
        run: |
          npm ci
          npm test
      
      - name: Build app
        run: npm run build

      - name: Restart Server
        run: pm2 restart server