name: CI

on:
  push:
    branches:
      - '**' # Matches every branch.

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Node.js Setup
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: Build
        run: |
          npm ci
          npm test